### ISSUE TITLE
docker's jekyll/jekyll:pages (and jekyll/jekyll:latest) can't find rake in current setup

### ISSUE THREAD

**Issue by moutons** [tirefire/tirefi.re#84]
jekyll's docker image can't find rake, apparently. I updated the Gemfile because that hasn't been done in a while and apparently this is still a problem?

```
➜  tirefi.re git:(fix-build) ✗ make fire-up
Recreating tirefire_tirefire_1 ...
Recreating tirefire_tirefire_1 ... done
➜  tirefi.re git:(fix-build) ✗ make fire-logs
Attaching to tirefire_tirefire_1
tirefire_1  | bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
tirefire_1  | Bundler::GemNotFound: Could not find rake-12.1.0 in any of the sources
tirefire_1  |   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize'
tirefire_1  |   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
tirefire_1  |   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
tirefire_1  |   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
tirefire_1  |   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
tirefire_1  |   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
tirefire_1  |   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
tirefire_1  |   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
tirefire_1  |   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
tirefire_1  |   /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
tirefire_1  |   /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
tirefire_1  |   /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
➜  tirefi.re git:(fix-build) ✗
```

**Comment by moutons** [comment]
I say "problem?" because maybe it's time to replace jekyll with something less obviously busted like MS FrontPage or maybe abandon the static site in favor of Joomla or something.
